### ISSUE TITLE
Chinese language problems

### ISSUE THREAD

**Issue by HoxtonK** [justrealmilk/braytech.org#4]
chinese cannot be displayed when chinese is selected
changing zh-chs  folder to zh-CHS can display
but the error is reported on the character-select page

**Comment by justrealmilk** [comment]
![image](https://user-images.githubusercontent.com/156681/68994975-63e0fe80-08d4-11ea-940b-beebd6c71cf6.png)

this is due to me trying to append more icon replacements at https://github.com/justrealmilk/braytech.org/blob/master/src/utils/destinyUtils.js#L572

an unhandled error is thrown at line 589 because the regex used at line 544 doesn't account for the letters used in the progress descriptions of the objectives i chose

i haven't worked out the characters to use to increase the range correctly yet (the last bit of the regex).

**Comment by HoxtonK** [comment]
Thanks for the update. I really like braytech.
I used it to get a lot of help in the destiny2.
